eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
server:
  port: 9000
spring:
  application:
    name: service-ribbon
#全局设置超时时间
ribbon:
  ConnectTiom: 2000
  ReadOutTime: 3000
#指定某个服务的超时时间
hello-service:
  ribbon:
    ConnectTiom: 2000
    ReadOutTime: 3000

