eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
server:
  port: 9000
spring:
  application:
    name: service-ribbon
##########开启缓存##############
hystrix:
  command:
    default:
      requestCache:
        enabled: true

