server:
  port: 1111

eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/
   #   defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/