spring:
  application:
    name: config-server
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: springcloud
  profiles:
  #    active: native #使用本地文件系统，不适用Git或svn
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhoutaiwei/spring_cloud_parent/ #配置git仓库地址
          #search-paths: foo,bar* 当配置文件可能反正 子目录时，Config Server 会在 根目录，foo子目录和所有bar开头的 目录去找
          searchPaths: config-repo #配置仓库路径
          username: zhoutaiwei #访问git仓库的用户名
          password: z6281350 #访问git仓库的用户密码
          basedir: E:/git_tmp #使用Git或SVN，文件都会在本地存储一份，这是指定存储的路径
          clone-on-start: true #可帮助Config Server启动时快速识别错误原因（如无效的Git仓库）
        native:
    #      search-locations: classpath:/config-repo/ #使用本地文件系统，指定文件的路径，和Git二选一
      label: master  #配置仓库的分支
    #  user: user #安全校验，检验输入的安全信息是否正确
    #  password: password

server:
  port: 7001
security:
  user:
   # name: user #设置安全保护，指定用户登录账户和密码
   # password:
encrypt:
  key: foo #对称密钥，用于加解密，发送post请求 127.0.0.1:7001/encrypt加密，127.0.0.1:7001/decrypt解密
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/ #配置注册服务中心
hystrix:
  threadpool:
    default:
      coreSize: 10

